# Move file to ~/.config/lazygit and rename file to config.yml
keybinding:
  universal:
    prevItem-alt: l
    nextItem-alt: k
    prevBlock-alt: j
    nextBlock-alt: Ã¸

customCommands:
  - key: 'V'
    context: 'files'
    command: 'code --goto {{.SelectedFile.Name}}'
    description: 'Open in VS Code'
